<?php

/**
 * Implements hook_menu().
 */
function ezsteps_glue_menu() {

  // Blank Home Page.
  $items['home'] = array(
    'access callback' => TRUE,
    'page callback' => 'ezsteps_glue_home_page',
    'title' => t('Welcome to Intel Easy Steps'),
  );

  $items['403-error'] = array(
    'access callback' => TRUE,
    'page callback' => 'ezsteps_glue_403_page',
    'title' => t('Access Denied'),
  );
  
  $items['admin/config/content/ezsteps/settings'] = array (
  	'title' => 'Easy Steps settings',
    'description' => 'Video preference',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ezsteps_glue_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
 
  return $items;
}

/**
 * Page callback for a blank home page.
 * 
 * We'll handle this page with blocks.
 */
function ezsteps_glue_home_page() {
  global $user;
  if ($user->uid) {
    drupal_goto('module-list');
  }
  return array();
}

/**
 * 403 Callback.
 */
function ezsteps_glue_403_page() {
  global $user;
  if ($user->uid) {
    return "<h2>Access Denied</h2><p>We're Sorry.  You don't have permission to access that page.</p>";
  }
  else {
    unset($_GET['destination']);
    drupal_goto('home');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adjusts the login form.
 */
function ezsteps_glue_form_user_login_block_alter(&$form, &$form_state, $form_id) {
  $form['name']['#title_display'] = 'invisible';
  $form['name']['#attributes']['placeholder'] = t('Email Address');
  $form['pass']['#title_display'] = 'invisible';
  $form['pass']['#attributes']['placeholder'] = t('Password');
  $form['links']['#markup'] = l(t('Forgot User Name or Password'), 'user/password');
  $form['#submit'][] = 'ezsteps_glue_login_destination';
}

/**
 * Sends users who just logged in to the homepage.
 */
function ezsteps_glue_login_destination(&$form, &$form_state) {
  $form_state['redirect'] = 'home';
  unset($_GET['destination']);
}

/**
 * Implements hook_form_FORM_ID_alter().
 * 
 * Adjusts the registration form.
 */
function ezsteps_glue_form_user_register_form_alter(&$form, &$form_state) {

  global $user;

  // If you're registering...
  if (!$user->uid) {
    // Add a title.
    $form['top_text'] = array(
      '#markup' => "<h2 id='ezsteps-registration-title'>" . t('Sign Up For Easy Steps') . '</h2>',
      '#weight' => -9990,
    );

    // Hide the username field.
    $form['account']['name']['#type'] = 'hidden';
    $form['account']['name']['#required'] = FALSE;

    // Remove the description for the email.
    $form['account']['mail']['#description'] = '';

    // Hide the 2nd password field.
    $form['account']['pass']['#type'] = 'password';
    $form['account']['pass']['#title'] = t('Password');
    $form['account']['pass']['#description'] = '';
    $form['account']['pass']['#size'] = '60';

    $form['agree_to_terms'] = array(
      '#weight' => 100,
      '#type' => 'checkbox',
      '#title' => t('I have read and understand the <a href="/privacy-statement">Privacy Statement</a>, and agree and accept the <a href="/terms-of-use">Terms of Use</a>.'),
      '#required' => TRUE,
    );

    // We need to copy over the email address as a username. Use a validate
    // function to do this.
    array_unshift($form['#validate'], 'ezsteps_glue_fix_username');
  }
}

/**
 * A form alter and submit handler function for the password reset to 
 * send the user to the home page after a password reset request.
 */
function ezsteps_glue_form_user_pass_alter(&$form, &$form_state, $form_id) { 

	$form['#submit'][] = '_ezsteps_glue_form_user_pass_custom_submit';    
}

function _ezsteps_glue_form_user_pass_custom_submit($form, &$form_state) {
    $form_state['redirect'] = array('home');
}

/**
 * A validate function for the registration form, though it doesn't actually
 * validate anything.  Instead, we just dump the email field into the username
 * field so that everything else will validate later on.
 */
function ezsteps_glue_fix_username(&$form, &$form_state) {
  $form_state['input']['name'] = $form_state['input']['mail'];
  $form_state['values']['name'] = $form_state['values']['mail'];
}

/**
 * Uses an EntityFieldQuery to load a module given its module number.
 */
function ezsteps_glue_get_module_by_number($module_number) {
  // Use drupal_static() so that the query is only run once per module per page
  // request.
  $module = &drupal_static(__FUNCTION__ . $module_number);

  // If this is the first time, query the DB for the nid.
  if (empty($module)) {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node');
    $query->entityCondition('bundle', 'module');
    $query->fieldCondition('field_module_number', 'value', $module_number);
    $result = $query->execute();
    if (!$result) {
      $module = FALSE;
    }
    else {
      $module = node_load(array_pop(array_keys($result['node'])));
    }
  }

  return $module;
}

function ezsteps_glue_admin() {

  $form = array();
  
  $form['ezsteps_video'] = array(
    '#type' => 'checkbox',
    '#description' => 'Check if videos are served from Drupal instead of Brightcove. For internal videos, also enable ezstepsVideoControls.js in ezsteps.info',
    '#title' => t('Internal video'),
    '#default_value' => variable_get('ezsteps_video', '0'),  );

  return system_settings_form($form);
}

/**
 * Hide persona selection on the profile page.
 */
function ezsteps_glue_form_user_profile_form_alter(&$form, &$form_state) {
	hide($form['field_user_persona']);
}
