<?php

/**
 * Implements ezsteps_menu().
 */
function ezsteps_certificate_menu() {
  $items['complete/%'] = array(
    'access callback' => 'ezsteps_certificate_is_module_complete',
    'access arguments' => array(1),
    'page callback' => 'ezsteps_certificate_complete_page',
    'page arguments' => array(1),
    'title' => 'Module Complete!',
  );

  $items['certificate/%'] = array(
    'access callback' => 'ezsteps_certificate_is_module_complete',
    'access arguments' => array(1),
    'page callback' => 'ezsteps_certificate_print',
    'page arguments' => array(1),
    'title' => 'Module Complete!',
  );

  return $items;
}

/**
 * Access control function to check if a user has completed a module.
 */
function ezsteps_certificate_is_module_complete($module_num, $uid = NULL) {
  // If no uid is provided, get the current user's.
  if (empty($uid)) {
    global $user;
    $uid = $user->uid;
  }

  // Load the module, if it can't be found, access denied.
  $module = ezsteps_glue_get_module_by_number($module_num);
  if (empty($module)) {
    return false;
  }

  // Pull up a list of flags that the user has on this contnet.
  $flags = flag_get_user_flags('node', $module->nid, $uid);

  // return true if they have the complete flag, false otherwise.
  return !empty($flags['module_complete']);
}

/**
 * Page callback for the module completed page.
 * 
 * @param integer $module_num
 *   The number of the module the user has completed.
 */
function ezsteps_certificate_complete_page($module_num) {
  $module = ezsteps_glue_get_module_by_number($module_num);
  $complete_header = t('Congratulations You\'ve Completed Module') . $module_num . ': ' . t($module->title);
  $download_text = t('Be sure to download and save, or print, your Journal page for your records.');
  return theme('ezsteps_complete_page', array(
        'complete_header' => $complete_header,
        'download_text' => $download_text,
      ));
}

/**
 * Implements hook_theme.
 * 
 * Registers the template files for the complete page and the certificate.
 */
function ezsteps_certificate_theme() {
  $theme['ezsteps_complete_page'] = array(
    'variables' => array(
      'module_num' => 0,
    ),
    'template' => 'templates/ezsteps_complete_page',
  );

  $theme['ezsteps_journal'] = array(
    'variables' => array(
      'module_num' => 0,
    ),
    'template' => 'templates/ezsteps_journal',
  );

  return $theme;
}

/**
 * Page callback for the certificate.
 * 
 * @param integer $module_num
 *   the module number that the user has completed.
 */
function ezsteps_certificate_print($module_num) {
  require_once(drupal_get_path('module', 'ezsteps_certificate') . '/dompdf/dompdf_config.inc.php');  
  // get the module info
  $module = ezsteps_glue_get_module_by_number($module_num); 
  // get the quiz info for the module
  $quiz = node_load($module->field_module_activities[LANGUAGE_NONE]['6']['target_id']);
  // get the responses 
  $responses = ezsteps_quiz_response_get($module_num);  
  $html = theme('ezsteps_journal', array(
    'module_num' => $module_num,
    'module_title' => $module->title,
    'question_a' => $quiz->field_quiz_open_ended_prompt[LANGUAGE_NONE][0]['safe_value'],
    'question_b' => $quiz->field_quiz_open_ended_prompt[LANGUAGE_NONE][1]['safe_value'],
    'response_a' => $responses[0]->response_a,
    'response_b' => $responses[0]->response_b,
    'radio_yes' => $responses[0]->radio_yes,
    'radio_np' => $responses[0]->radio_np,
  ));
  $dompdf = new DOMPDF();
  $dompdf->load_html($html);
  $dompdf->render();
  $dompdf->stream("sample.pdf");
  exit;
}