<?php

/**
 * Implements hook_node_view().
 * 
 * Adds the quiz js to the node.
 */
function ezsteps_quiz_node_view($node) {
  if ($node->type == 'quiz') {
    drupal_add_js(drupal_get_path('module', 'ezsteps_quiz') . '/js/quiz.js');
    
    $form = drupal_get_form('ezsteps_quiz_open_ended_form', $node);
    
    // Add the open ended and radio questions to the empty field so it will display in 
    // the tab
    $node->content['field_quiz_journal_form'] = array(
      '#markup' => render($form),
    );
  }
}

function ezsteps_quiz_open_ended_form($form, $form_state, $node) {

  $header = '<h3>'. t('For Your Journal') .'</h3>'. $node->field_radio_question[LANGUAGE_NONE][0]['safe_value'];
  
  $form['header'] = array(
  	'#type' => 'item',
  	'#markup' => $header	,
  );

  // set up the radio button questions
  $i = 0;
  foreach ($node->field_radio_question_prompt[LANGUAGE_NONE] as $radio_prompt)  {	  
	  $form['open_ended']['radios'][$i] = array(
	    '#type' => 'radios',
	    '#title' => t($radio_prompt['value']),
	    '#title_display' => 'invisible',
	    '#required' => TRUE,
	    '#prefix' => '<div id="ezsteps-radio-prompt">' . $radio_prompt['value'] . '</div>',
	    '#options' => array('1' => t('Yes'),'0' => t('Needs Practice')),
	  );
	  $i++;	  	
  }

  // set up the open ended response questions
  $i = 20;
  foreach ($node->field_quiz_open_ended_prompt[LANGUAGE_NONE] as $open_ended_prompt)  {
	  $form['open_ended']['text'][$i] = array(
	    '#type' => 'textarea',
	    '#required' => TRUE,
	    '#prefix' => '<div id="ezsteps-open-ended-prompt">' . $open_ended_prompt['value'] . '</div>',
	  );
	  $i++;	  	
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return $form;
}

function ezsteps_quiz_open_ended_form_submit($form, &$form_state) {
  global $user;

  // go through the radio questions and separate into yes and needs practice responses
  //
  $i = 0;
  $yes = '';
  $needs_practice = '';
  foreach ($form['open_ended']['radios'] as $key => $radio_prompt)  {
	  
	 if (is_int($key)) {
		  if ($radio_prompt['#value'] == '0') {
			  $needs_practice .= $radio_prompt['#title'] . '|';
		  } else {
			  $yes .= $radio_prompt['#title'] . '|';
		  }
		  $i++;
      }
  }
  
  $response_a = (empty($form['open_ended']['text']['20']['#value']) ? '' : $form['open_ended']['text']['20']['#value']);
  $response_b = (empty($form['open_ended']['text']['21']['#value']) ? '' : $form['open_ended']['text']['21']['#value']);
  $query = db_merge('ezsteps_quiz_response')
      ->key(array(
        'uid' => $user->uid,
        'module_num' => arg(1),
      ))
      ->fields(array(
        'response_a' => $response_a,
        'response_b' => $response_b,
        'radio_yes' => $yes,
        'radio_np' => $needs_practice,
      ))
      ->execute();

  // TEMP: Flag this module as complete, until we get better requirements.
  // Load the module
  $module = ezsteps_glue_get_module_by_number(arg(1));
  $flag = flag_get_flag('module_complete');
  $flag->flag('flag', $module->nid);
  
  $form_state['redirect'] = 'complete/' . arg(1);
}

function ezsteps_quiz_response_get($module_num, $uid = NULL) {
  if (is_null($uid)) {
    global $user;
    $uid = $user->uid;
  }

  $result = $query = db_select('ezsteps_quiz_response', 'ezqr')
          ->fields('ezqr', array('response_a', 'response_b','radio_yes','radio_np'))
          ->condition('ezqr.module_num', $module_num)
          ->condition('ezqr.uid', $uid)
          ->execute()->fetchAll();

  if (empty($result)) {
    return FALSE;
  }
  return $result;
}